# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.



main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Materiais
    identifier: mat
    weight: 20
  # - name: EM
  #   parent: ferr
  #   url: '#em'
  #   weight: 10
  - name: Ensino MÃ©dio
    parent: mat
    url: '#medio'
    weight: 10
  - name: Ensino Superior
    parent: mat
    url: '#superior'
    weight: 20
  - name: Contato
    url: '#contato'
    weight: 60

###################################

# # Menu velho
# main:
#   - name: Home
#     url: '#about'
#     weight: 10
#   - name: Ferramentas
#     identifier: ferr
#     weight: 20
#   # - name: EM
#   #   parent: ferr
#   #   url: '#em'
#   #   weight: 10
#   - name: Programas
#     parent: ferr
#     url: '#programas'
#     weight: 20
#   - name: Contato
#     url: '#contato'
#     weight: 60
# 
# ###################################
